services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=pms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      - web

  angular:
    build:
      context: ./pms-hotel
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    networks:
      - web
    command: npm run start

networks:
  web:
    name: web
    driver: bridge
    attachable: true
    external: true
